#!/bin/bash
TARGET=$1
TARGETSTEM=${TARGET%%.cgi}
cd src
ghc -package cgi -package xhtml -fallow-overlapping-instances --make -o $TARGET $TARGETSTEM.hs $(find . -name '*.hs' | grep -Ev 'Installdb\.hs|Blog\.hs|Migrate\.hs|settingsl.*\.hs') || exit 1
chmod ugo+rwx $TARGET
if [ ! "$TARGETSTEM" == "$TARGET" ]
then
	mv $TARGET /home/luke/httpd/lukeplant.me.uk/web/cgi-bin/$TARGET
fi
