        </div>
      </div>
      <div id="footer">
        <h1>Links</h1>
	<div class="bloglinks">
	  <h2>Blog links:</h2>
          <ul>
            <li><a href="/blog/">Index</a></li>
            <li><a href="/blog/feeds/">Feeds</a></li>
            <li><a href="/blog/categories/">Categories</a></li>
            <li><a href="/blog/about/">About blog</a></li>
          </ul>
	</div>
        <div class="sitelinks">
          <h2>Also on this site:</h2>
          <ul>
            <li><a href="/" >Index</a></li>
            <li><a href="/softprojects.html">Software</a></li>
            <li><a href="/bibleverses/">Bible memorisation</a></li>
            <li><a href="/personal.html">About me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </body>
</html>

