        </div>
      </div>
      <div id="footer">
      <p>Copyright <a href="mailto&#58;L.Plant.98&#64;cantab.net">Luke Plant</a></p>
      </div>
      <div id="loginlinks">
        <a href="/blog/login/?r=$currentpath$" id="id_loginlink">Login</a><br/>
        <a href="/blog/logout/?r=$currentpath$" id="id_logoutlink">Logout</a><br/>
        <a href="/blog/admin/">Admin</a><br/>
        $if(editpageurl)$
          <a href="$editpageurl$">Edit</a><br/>
        $endif$
      </div>
      <div id="responsebox" style="display:none;">
        <ul>
          <li>Didn't read the post</li>
          <li>Troll!</li>
          <li>Off-topic</li>
          <li>Already answered in comments</li>
        </ul>
        Custom: <input type="text" id="responseinput" size=50> <input type="submit" id="responsesubmit" value="Send"> <input type="submit" id="responsecancel" value="Cancel">
        <input type="hidden" id="responsecommentid" value="">
      </div>
    </div>
<script type="text/javascript"> 
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script> 
<script type="text/javascript"> 
try {
var pageTracker = _gat._getTracker("UA-6741729-1");
pageTracker._trackPageview();
} catch(err) {}</script>
  </body>
</html>

